### ISSUE TITLE
masks of test images?

### ISSUE THREAD

**Issue by a83376114** [nicolaihaeni/MinneApple#10]
I think there should have masks on test images, but i didn't find it in detection.zip.

**Comment by nicolaihaeni** [comment]
We do not release the test masks so as to not compromise the benchmark. For testing, please use the provided servers here: 

Fruit detection: https://competitions.codalab.org/competitions/21718
Fruit segmentation: https://competitions.codalab.org/competitions/21694
Fruit counting: https://competitions.codalab.org/competitions/21719

**Comment by a83376114** [comment]
I know,thanks
