### ISSUE TITLE
No masks for test set

### ISSUE THREAD

**Issue by yotamraz** [nicolaihaeni/MinneApple#11]
I think there should be a mask folder within the test set, can't find them within the detection.tar.gz file.

**Comment by nicolaihaeni** [comment]
Hi

We do not publicly share labels for the testset, but if you would like to test your results, we provide Codalab servers for that.
You can test your results here: [Detection](https://competitions.codalab.org/competitions/21718),  [Segmentation](https://competitions.codalab.org/competitions/21694) and [Counting](https://competitions.codalab.org/competitions/21719)
