### ISSUE TITLE
Where can I find the raw image and labeled images dataset

### ISSUE THREAD

**Issue by VegetarianLion258** [nicolaihaeni/MinneApple#12]
Hi, I am trying to make a CNN to detect the position of apples, but I am lack in dataset. Could you share the apple dataset that you use in that paper?Thanks a lot.

**Comment by nicolaihaeni** [comment]
Hi

The dataset is available here:
https://conservancy.umn.edu/handle/11299/206575

**Comment by VegetarianLion258** [comment]
Thank you very much for your help.
