### ISSUE TITLE
How to use this dataset to Semantic segmentation

### ISSUE THREAD

**Issue by plainzzj** [nicolaihaeni/MinneApple#14]
In the paper, I saw that the semantic segmentation method (U-Net) was used for training，
How is this part implemented in code? 
How to convert the pixel value (classes lable) of instance segmentation into semantic segmentation?
 Thank you very much.

**Comment by SonwYang** [comment]
Hello, you can use numpy library to do it. For example, 
"seg_label = np.where(ins_label > 0, 1, 0)"
