### ISSUE TITLE
Raw video and camera parameters

### ISSUE THREAD

**Issue by Augusthyq** [nicolaihaeni/MinneApple#16]
Thank you very much for your work. May I request a copy of the original high-definition full video? Also, could you please let me know the internal parameter configuration of the camera? Thank you very much.

**Comment by nicolaihaeni** [comment]
Hi

The data that is officially published is all that is released. We do not plan to release the videos. The data was captured long ago (2015-2017), and I do not have the intrinsic camera parameters.
