### ISSUE TITLE
How arrive from Detection/Segmentation to Counting

### ISSUE THREAD

**Issue by schmidarnold** [nicolaihaeni/MinneApple#2]
I have a general question about the MinneApple DataSet. The Detection/Segmentation process is clear. As a result we detect the single fruits on the tree. But how we can count the apples on the tree? I mean your approach of counting is a classifying algorithm. You have images and you classify them  (1 apples, tuples....5apples). But in the detection process we have only single apples. How we can count the apples? I mean, how want you combine this two approaches to count apples on an given image? 
Thanks
Arnold (Italy)

**Comment by nicolaihaeni** [comment]
Hi Arnold
There are multiple ways to count the fruits. You could just sum up the detections, but the detection algorithm might merge multiple detections together. This can make a second counting stage necessary, where you count the number of fruits in each detected bounding box. 
For more information, check out the following papers:
1.  [Apple Counting using Convolutional Neural Networks ](https://ieeexplore.ieee.org/document/8594304)
2. [A comparative study of fruit detection and counting methods for yield mapping in apple orchards](https://onlinelibrary.wiley.com/doi/full/10.1002/rob.21902)

These papers give an overview of the necessary steps for a complete fruit yield estimation pipeline, including tracking of fruits across frames (which is not part of this repository). The papers also address why one might want to employ a separate algorithm for counting on top of fruit detection.

I hope this helps

**Comment by schmidarnold** [comment]
Thank you Nicolai for the immediate response. I will read the papers referenced by your links. Very helpful your work about apple counting, because works about machine learning and agriculture are very sparse. I am apple farmer on my own and therefore finding a solution for counting the apples on a tree could be very helpful.
Thank you again.

**Comment by nicolaihaeni** [comment]
If you are interested in a commercial solution for this problem, we have recently founded a spin-off company to commercialize these algorithms. You can find more information and contact information here: [https://farm-vision.com/](https://farm-vision.com/)
