### ISSUE TITLE
Loading other pre-trained networks

### ISSUE THREAD

**Issue by felipevw** [nicolaihaeni/MinneApple#4]
Hi, 
I was trying to change the models of the train_rcnn to some of the detectron2. I changed only the backbone but I am always getting an error in the same place, in the
`train_one_epoch()` in the line `loss_dict = model(images, targets)`. Maybe something was modified in that function.
It tells:

> IndexError: list index out of range

Also, when I print the default mrcnn model, why the (box_predictor), has 8 output features? Shouldn't be 4 for the 2 points?

> (bbox_pred):` Linear(in_features=1024, out_features=8, bias=True)

I changed this part of the code when I inserted a new backbone:
```

def get_R50_model(num_classes):
    
    
    # Get the model from detectron2
    model = get_cfg()
    model.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
    model.DATALOADER.NUM_WORKERS = args.workers
    model.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
    model.MODEL.ROI_HEADS.NUM_CLASSES = 1
    
    detectron_model = build_model(model)
    
      
    
    # load an instance segmentation model pre-trained pre-trained on COCO
    py_model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
    
    
    # get number of input features for the classifier
    in_features = py_model.roi_heads.box_predictor.cls_score.in_features
    # replace the pre-trained head with a new one
    py_model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)

    # now get the number of input features for the mask classifier
    in_features_mask = py_model.roi_heads.mask_predictor.conv5_mask.in_channels
    hidden_layer = 256
    # and replace the mask predictor with a new one
    py_model.roi_heads.mask_predictor = MaskRCNNPredictor(in_features_mask, hidden_layer, num_classes)
    
    # Exchange backbones
    py_model.backbone = detectron_model.backbone
    
    
    return py_model
```

Thank you for the help

**Comment by nicolaihaeni** [comment]
Hi 

I don't know the detectron2 implementation of maskrcnn, but I could imagine that it is slightly different to the standard pytorch one. In general, you can not use a detectron backbone/weights with a standard PyTorch one. You should use the detectron code/model instead. Alternatively, you can use different pytorch models as backbones. This is a good tutorial to get started: https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html

Hope this helps

**Comment by felipevw** [comment]
So I guess there are two possible options, either reuse the detectron code or convert MinneApple from images and masks to a coco dataset format. Maybe the best will be to stay in Pytorch to keep things simple.

Thank you
