### ISSUE TITLE
State loading issue

### ISSUE THREAD

**Issue by Muhtasham** [nicolaihaeni/MinneApple#5]
Hi thank you for sharing your work,
While trying to replicate your results i faced following problem:
in **train_rcnn.py**, i uncommented eval() function and trained for 50 epochs (both frcnn and mrcnn), however while trying to load states, i got the errors below.

![image](https://user-images.githubusercontent.com/20128202/87024247-861be980-c1e1-11ea-941b-8e31c9dce3cd.png)
![image](https://user-images.githubusercontent.com/20128202/87024293-946a0580-c1e1-11ea-8b7b-3979e82d422f.png)

For your reference below are the links for the latest checkpoints:
_https://drive.google.com/file/d/128HDnr5P3CvzX_HBKWdSG-6kMpS4DwjA/view (frcnn)_
_https://drive.google.com/file/d/12BKIH_zLeP69t4RHGZk7NbMgykLlVDH8/view (mrcnn)_

Can you please help,
Thank you for your time

**Comment by Muhtasham** [comment]
import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
num_classes = 2
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
in_features = model.roi_heads.box_predictor.cls_score.in_features
model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
model.to(device)
checkpoint = torch.load('path to check point', map_location='cpu')
model.load_state_dict(checkpoint['model'])
model.eval()
clear_output()

**Comment by cuge1995** [comment]
I solved this by `model.load_state_dict(torch.load(model_path))`
