### ISSUE TITLE
Replicating results

### ISSUE THREAD

**Issue by esgnn** [nicolaihaeni/MinneApple#6]
Hi, 

Thank you for sharing your work. 
I am wondering, is the training code you've provided enough to replicate your results? 
I am having a very low score with your implementation at test evaluation (at competition).
Thank you for your time

**Comment by nicolaihaeni** [comment]
Hi 

The training code is merely an example of how to load/train a model. For a detailed description of the parameters used in the experiments in the paper I refer you to the following paper: https://onlinelibrary-wiley-com.ezp1.lib.umn.edu/doi/full/10.1002/rob.21902. 

Hope this helps. 
Nicolai

**Comment by esgnn** [comment]
Ah, thank you! I'll look into it. 
The link is behind the university system, here is the arxiv link to anyone who might be interested. 
https://arxiv.org/abs/1810.09499
