### ISSUE TITLE
Cannot load trained model

### ISSUE THREAD

**Issue by F2Wang** [nicolaihaeni/MinneApple#7]
Hi,

Thank you for sharing your work, and for labeling the dataset (looks like a lot of hard work).

I encounter a problem with loading the trained .pth file for evaluating.  Speficifally the error looks like:
model.load_state_dict(checkpoint['model'], strict=False)
KeyError: 'model'

I will appreciate any suggestions on the problem.

Thanks

**Comment by nicolaihaeni** [comment]
Hi

Could you provide some additional information? Namely, how do you save the model to the .pth file? And how is your model created?

**Comment by F2Wang** [comment]
Hi thanks for getting back to me so quickly! I got the model directly from running python train_rcnn.py --data_path /path/to/MinneApple/dataset --model mrcnn --epochs 50 --output-dir /path/to/checkpoint/directory

Could this be a torch version issue? I am on version 1.1.0...

**Comment by nicolaihaeni** [comment]
No this is an issue in the code. I just pushed a fix, I was loading the model differently from what was actually saved. To avoid retraining of your model, you should be able to just load the model like this:
model.load_state_dict(torch.load(PATH))

If you actually need the optimizer and scheduler state, I am afraid you will have to retrain the model with the newly pushed changes. 

Hope this helps

**Comment by F2Wang** [comment]
Hi Nicola,

Thanks! I just fixed the problem, it's similar to this but you also need to have strict = False at the end, otherwise, It will report a problem about missing parameters.
