### ISSUE TITLE
When I train the data set, I report an error

### ISSUE THREAD

**Issue by shangmou** [nicolaihaeni/MinneApple#9]
masks = torch.as_tensor(masks, dtype=torch.uint8)
TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.

**Comment by nicolaihaeni** [comment]
Hi 

What format are your masks in? We require an unsigned integer mask (similar to an image) with values in the range 0-255. It looks like your mask is in boolean format. 

Hope this helps.
